# Generated by Django 5.2.4 on 2025-07-29 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('service_type', models.CharField(max_length=100)),
                ('date_completed', models.DateField()),
                ('client', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
